name: CI/CD for Data Ingestion Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/data_ingestion/**'
      - 'tests/unit/test_data_ingestion.py'
      - 'infrastructure/**' # Rerun on any infrastructure change
  pull_request:
    paths:
      - 'src/data_ingestion/**'
      - 'tests/unit/test_data_ingestion.py'

jobs:
  test-and-validate:
    name: Run Unit Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r src/data_ingestion/requirements.txt
          pip install pytest boto3
      
      - name: Run linter
        run: |
          pip install flake8
          flake8 src/data_ingestion/

      - name: Run unit tests
        run: pytest tests/unit/test_data_ingestion.py

  deploy-to-aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test-and-validate
    if: github.ref == 'refs/heads/main' # Only run on merge to main
    
    permissions:
      id-token: write # Required for AWS OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy-role # Replace with your OIDC role
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        id: apply
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve

      # Placeholder for integration test - requires more setup
      # - name: Run Integration Test
      #   run: |
      #     pip install pytest boto3
      #     python -m pytest tests/integration/test_ingestion_pipeline.py --api-url ${{ steps.apply.outputs.api_endpoint_url }}